# Entry point HTML file.
html_path: './index.html'

# Whether to show the window above/below all others.
# Allowed values: 'always_on_top', 'always_on_bottom', 'normal'.
z_order: 'normal'

# Whether the window should be shown in the taskbar.
shown_in_taskbar: false

# Whether the window should have resize handles.
resizable: false

# Where to place the window.
default_placements:
  # The monitor index to place the window on.
  # Allowed values: 0, 1, 2, 3, etc. OR 'all'.
  - monitor_index: 0
    # Allowed values: 'top', 'bottom', 'left', 'right'.
    position: 'top'
    offset_x: 20
    offset_y: 20
